alias ..='cd ..'
alias a='./a.out'
alias ag='sudo apt-get'
alias arduino='sudo ~/arduino-1.0.5/arduino'
alias c='clear'
alias cb='vim ~/.bashrc'
alias ch='chmod 700'
alias ct='cat'
alias cv='vim ~/.vimrc'
alias chromium='chromium-browser'
alias chrome='google-chrome'
alias d='cd'
alias doc='cd ~/Documents'
alias decrypt='gpg'
alias encrypt='gpg -c'
alias earth='google-earth-stable'
alias g='git'
alias gc='clear && gcc -g'
alias gd='clear && gdb'
alias gda='clear && gdb ./a.out'
alias j='/home/ec2-user/julia-binary/usr/bin/julia-readline'
alias julia='/home/ec2-user/julia-binary/usr/bin/julia-readline'
alias la='ls --color=auto -a'
alias l='ls --color=auto'
alias lsa='ls -la --color=auto'
alias mk='mkdir'
alias o='okular'
alias psa='ps aux | grep '
alias py='python3'
alias py2='/usr/bin/python'
alias python2='/usr/bin/python'
alias scheme='mit-scheme'
alias sublime='~/Sublime\ Text\ 2/sublime_text'
alias subl='~/Sublime\ Text\ 2/sublime_text'
alias v='vim'
alias ls='ls --color=auto'
alias t='touch'
alias tor='~/tor/startTor'
alias wh='which'
alias update='cd;g add .bashrc .vimrc .startup .gitconfig; g cm -m "update"; g push;'

